#!/usr/bin/env bash

set -eu
set -o pipefail

SFX="$1"

diff <(grep "K[ ]*EFF" qa/snestp*.out${SFX} | tr -s " " | cut -d" " -f4) ./reference${SFX}

diff qa/snestp011.flx${SFX} snestp011.flxref${SFX}

echo "Pass"
