[project]
name = "docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ford>=7.0.9",
    "graphviz>=0.20.3",
    "lxml>=5.3.1",
]
