name: Docs

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.10"
      - name: Set up Python
        run: uv python install
      - name: Build docs
        run: |
          set -e
          uv run make -C docs html
      - name: Deploy docs via SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DOCS_SSH_PRIVATE_KEY }}
      - name: Disable strict host key checking
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - run: |
          rsync -avz --delete docs/html/ ${{ secrets.DOCS_SSH_USER }}@${{ secrets.DOCS_SSH_HOST }}:${{ secrets.DOCS_SSH_PATH }}
