#!/usr/bin/env bash

set -eu
set -o pipefail
#set -x

VERSION="$1"
SFX="$2"  !! Suffix used for output file naming (e.g., distinguishing sweep types)
TPNAME="$(basename "${3:-$2}" .in)"

JOBID=$$

echo "Starting job ${JOBID}"

BASEDIR=$(pwd)

INDIR=${BASEDIR}
INPUT=${INDIR}/qa/${TPNAME}.in

OUTDIR=${BASEDIR}/qa/tpx${JOBID}
OUTPUT=${TPNAME}.out${SFX}
FLXDAT=${TPNAME}.flx${SFX}

AOUTDIR=${BASEDIR}
AOUT=${AOUTDIR}/sne${SFX}${VERSION}

mkdir -p "${OUTDIR}"
cd "${OUTDIR}"

cp "${AOUT}"  ./a.out
cp "${INPUT}" ./snes.in

NUCDIR="${BASEDIR}/nucdata"
for NUC in 19423901 29423901 19223501 29223501 126nat01 111nat01 \
           1h2o__01 2h2o__01 1u-d2o01 11212301 21212301 41212301 ; do
  cp "${NUCDIR}/a${NUC}.dat"   "./${NUC}.dat"
done

./a.out > snes.out 2>&1

{                                                           # skip
echo "---------------------------------------------------"  # skip
echo "JCF                                                "  # skip
echo "---------------------------------------------------"  # skip
grep -v '# skip$' "${BASEDIR}/$0"                           # skip
echo                                                        # skip
echo "---------------------------------------------------"  # skip
echo "INPUT                                              "  # skip
echo "---------------------------------------------------"  # skip
cat snes.in                                                 # skip
echo                                                        # skip
echo "---------------------------------------------------"  # skip
echo "OUTPUT                                             "  # skip
echo "---------------------------------------------------"  # skip
cat snes.out                                                # skip
echo                                                        # skip
echo "---------------------------------------------------"  # skip
echo "RESOURCES                                          "  # skip
echo "---------------------------------------------------"  # skip
} > "${OUTPUT}"                                             # skip

mv "${OUTPUT}" "${BASEDIR}/qa"
[[ -f flux1.dat ]] && mv flux1.dat "${BASEDIR}/qa/${FLXDAT}"

exit 0
